{
	"Animated": true,
	"Duration": 2,
	"Message": "Entity created",
	"IsIconHidden": true,
	"OnSuccess": "/CrudApp/Actions/CloseModalPage_Complete.action",
	"_Type": "Action.Type.ToastMessage"
}